default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  host: 127.0.0.1
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>

development:
  <<: *default
  database: test_development

test:
  <<: *default
  database: test_test

production:
  <<: *default
  host: <%=ENV["POSTGRES_HOST"] %>
  database: test_production